name: Publish Resource
description: Submit your resource
labels: []
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: "My resource is not using any assets that I have no ownership of"
          required: true
        - label: "My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset"
          required: true
  - type: textarea
    id: assets
    attributes:
      label: Resource information file
      description: "Make sure to completely fill the file"
    value: |
```yml
author: author
title: YourTitleHere
content: YourDescriptionHere
icon: imgurl url here (ends with .png)
banner: imgurl url here (ends with .png)
links:
- https://builtbybit.com/resources/xxxxxx
premium: false
tags: []
time: 1683711967
```
    render: yml
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this suggestion page!
