name: Publish Resource
description: Submit your resource
labels: []
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: "My resource is not using any assets that I have no ownership of"
          required: true
        - label: "My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset"
          required: true
  - type: textarea
    id: assets
    attributes:
      label: Resource information file (YML)
      description: "Make sure to completely fill the file with a valid YML"
      render: yml
      value: |
        author: author
        title: YourTitleHere
        content: YourDescriptionHere
        premium: false
        icon: imgurlUrlHere
        banner: imgurlUrlHere
        time: 2025-01-01
        links:
        - https://spigotmc.org/resources/xxxxxx
        - https://builtbybit.com/resources/xxxxxx
        tags:
        - items
        - blocks
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this suggestion page!
